id: I450DACCC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T03:20:27+00:00'
last_modified: '2022-06-08T03:18:43.650300+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG557
  title: གནོད་སྦྱིན་ཆེན་པོ་ཀྵེ་ཏྲ་པཱ་ལའི་ལྷ་ཚོགས་ལ་མཆོད་གཏོར་འབུལ་ཚུལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E621:
      image_group_id: I1KG561
      title: ''
      total_pages: 14
      order: 1
      base_file: E621.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
