id: P005470
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:52:16.371618
source_metadata:
  id: bdr:W1KG557
  title: གནོད་སྦྱིན་ཆེན་པོ་ཀྵེ་ཏྲ་པཱ་ལའི་ལྷ་ཚོགས་ལ་མཆོད་གཏོར་འབུལ་ཚུལ་
  author: ''
  volumes:
    5de8c498c272499abd67dceac5a10f60:
      image_group_id: I1KG561
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
